### PR TITLE
Added support for SystemJS Direct Trace API

### PR DESCRIPTION
**Pull request by JustinWilabyPrecor**
This PR adds support for the SystemJS direct trace API when creating a common dependencies bundle and updated the README.md to provide more build examples.

### CODE REVIEW

**Comment by ricog** [comment]
@JustinWilabyPrecor why did you close this? It looked useful.

**Comment by JustinWilabyPrecor** [comment]
I created a new project that I can directly support.  This will eventually add support for jspm 0.17 https://github.com/justinwilaby/grunt-jspm-builder

**Comment by ricog** [comment]
Thank you for the link @JustinWilabyPrecor. https://github.com/justinwilaby/grunt-jspm-builder allowed me to include a directory tree with ease. @smallhadroncollider perhaps `grunt-jspm-builder` supercedes `grunt-jspm`?

**Comment by smallhadroncollider** [comment]
@JustinWilabyPrecor @ricog I'll add a link to it in the Readme

**Pull request closed without merging**
